### ISSUE TITLE
[BUG] 썸네일 이미지 업로드 방식 개선

### ISSUE THREAD

**Issue by jknadan** [FG-Academy/FG-Academy-FE#17]
### Describe bugs
- 기존에 [POST] localhost:3000/courses 로 코스에 대한 썸네일을 업로드하고, 그 경로를 Nest-tmp-storage 경로에 저장한 후, 그 경로를 DB에 저장하는 방식을 구현
- 그 후 NextJS에서 useQuery를 통해 DB의 이미지 경로를 가져온 후 컴포넌트에 뿌려주고자 했으나, NextJS에서 프로젝트 외부 경로에 있는 이미지는 가져오지 못하는 문제가 발생
- 이를 해결하기 위해 아래와 같은 방법을 통해 동작방식을 개선해야할 듯

1. 관리자가 코스 정보를 입력할 때, 썸네일 이미지를 업로드하면 FE 프로젝트 내부의 별도 이미지를 관리하는 폴더를 구성하고, 그 폴더 안에 이미지 파일을 저장할 수 있도록 한다.
2. 저장 후, 해당 경로를 BE에 POST 요청하여 그 경로를 DB에 저장한다.
3. 그럼 BE에 API 요청을 날려도 FE 프로젝트 내부의 경로를 반환하기 때문에 정상적으로 이미지를 표현할 수 있다.

#### TODO
- [ ] 관리자 페이지 구현 (구현 전에는 Dummy Data를 이용해야할 듯)
- [ ] 썸네일 이미지를 업로드하면 FE 프로젝트 내부 폴더에 저장하도록 구성
- [ ] 이미지 파일 저장 후, BE에 POST 요청 시 저장경로를 body에 포함하여 send
- [ ] BE는 해당 값을 DB에 저장
