### ISSUE TITLE
[Feature] 요청사항 모음

### ISSUE THREAD

**Issue by jknadan** [FG-Academy/FG-Academy-FE#72]
### Description
- 요청 사항을 모은 모음집
-  [x] 요청사항1: 관리자 페이지에서 회원삭제 기능을 추가하면 안되나?
-  [x] 요청사항2: 회원 정보 중, 직분에 ‘강도사’ 추가 요청

### TODO
- [x]  요청사항1: 관리자 페이지에서 회원삭제 기능을 추가하면 안되나?
- [x] 요청사항2: 회원 정보 중, 직분에 ‘강도사’ 추가 요청
